name: ci
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: node installation
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: install dependecies
        run: npm ci

      #   - name: test application
      #     run: npm run test:prod

      - name: build application
        run: npm run build


      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1.9.12
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}



