name: ci
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: node installation
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: install dependecies
        run: npm ci

      - name: test application
        run: npm test:prod

      - name: build application
        run: npm build:prod
